import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homepage",
<<<<<<< HEAD
  description: "Home of 411095",
=======
  description: "Generated by create next app",
>>>>>>> 6c1e9204363efd09f8e50d7f5655abb71006b7d9
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
